### ISSUE TITLE
Accepting pull requests?

### ISSUE THREAD

**Issue by MrMaz** [rayman1104/ra-data-nestjsx-crud#1]
Hello!

We are considering forking this module for the same reasons you have. Would prefer to collaborate with you if you are interested.

Please let us know if you plan to maintain and/or are accepting pull requests.

Thanks!

**Comment by rayman1104** [comment]
Hi!
I'm surprised that you found this repo since I didn't publish it anywhere (maybe I should tho). You are very welcome to send PRs here, do what you think is reasonable and I'll try to review :)

**Comment by MrMaz** [comment]
@rayman1104 thanks for replying :)

The trick is to go to Insights -> Network and you can see all the guys that have forked.

I will talk to my team and start testing your code.

Thanks again!
