### ISSUE TITLE
Headers in Data Provider

### ISSUE THREAD

**Issue by koaladlt** [rayman1104/ra-data-nestjsx-crud#21]
Hey there! First of all, thank you for maintaining this library.

I was trying to add an "Authorization Bearer" header to the Data Provider, but I'm not seeing in the docs a way to do it. 

Thanks in advance!

**Comment by rayman1104** [comment]
Hi! You should create your own httpClient and provide it as an argument to this data provider.
See the docs: https://marmelab.com/react-admin/Authentication.html#sending-credentials-to-the-api

**Comment by koaladlt** [comment]
@rayman1104 Thanks a lot!
