### ISSUE TITLE
Support case-insensitive comparison for filters

### ISSUE THREAD

**Issue by Brunni** [rayman1104/ra-data-nestjsx-crud#26]
According to nestjsx/crud it supports filter arguments for case-insensitive comparisons for strings:

https://github.com/nestjsx/crud/blob/bbea082a3f0fc7c1be42a79164f41b8449ad2251/packages/crud-request/src/types/request-query.types.ts

`CondOperator.CONTAINS_LOW ` is the filter type

It would be very helpful for searching/filtering on text columns.

Workaround code:
```
// TODO: This is a "hack" to pass $contL for filters where we want case insensitive search
      if (params.filter.buyer?.name) {
        debugger;
        const {
          buyer: { name: nameFilter },
          ...otherFilters
        } = filter;
        filter = { ...otherFilters, buyer: { ["name" + "||$contL"]: nameFilter } };
      }
```

**Comment by jstoeffler** [comment]
@Brunni Can you clarify where you add the workaround? I'd be interested in a similar solution for a different use case.

I use string enums, and I need the $eq operator, but it seems for string this library only uses $cont. It would be great to have an actual way to set this up, I may try a PR later, but I'd be happy with a hack for now.

**Comment by Brunni** [comment]
Hi! We are now fine with a different solution and can close this ticket now.

We use the filter type directly in the source tag of the filter input:
e.g.
```
const filters = [
  <TextInput source="id||$contL" alwaysOn />,
  <TextInput source="name||$contL" alwaysOn />,
];
```

**Comment by ockam** [comment]
Just came across the same issue (need to use a case insensitive filter) and the above suggestion (`source="name||$contL"`) doesn’t appear to work in React-Admin 4 (4.3.3); when I insert pipes in the source props, the input field stop accepting keystrokes.

I tried with `<TextInput>` and `<SearchInput>`.

I’ll try to work on a PR, but if you know another workaround, I’m listening. :)
