### ISSUE TITLE
How to install this fork

### ISSUE THREAD

**Issue by osikes** [rayman1104/ra-data-nestjsx-crud#6]
This branch is the only listed and claimed working integration between react-admin and nestjs. https://marmelab.com/react-admin/DataProviders.html 

How do I install this, given there is no version number in the package.json ?

**Comment by rayman1104** [comment]
To install using npm: `npm i ra-data-nestjsx-crud`
using yarn: `yarn add ra-data-nestjsx-crud`

Here is the version in the package.json: https://github.com/rayman1104/ra-data-nestjsx-crud/blob/master/packages/data-provider/package.json#L3
Here is the link to npm: https://www.npmjs.com/package/ra-data-nestjsx-crud

**Comment by osikes** [comment]
Thank you so much, that set me in the right direction 😄
